name: flutter_app_bfd_3
description: Networking and FutureBuilder (The Boring Flutter Development Show, Ep. 3)

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  http: ^0.12.0+2
  built_value: ^6.7.0
  built_collection: ^4.2.2
  url_launcher: ^5.1.2
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^1.6.6
  built_value_generator: ^6.7.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true